version: "3.8"
services:
  raznet:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./static:/app/static
    environment:
      - OLLAMA_HOST=http://localhost:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]

volumes:
  ollama-data: